import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import App from './App'
import { MultiProfileDock } from './components/MultiProfileDock'
import './styles.css'
import './kernel.css'
import './runtime.css'
import './credential.css'
import './diagnostics.css'
import './evidence.css'
import './adapter.css'
import './lifecycle.css'
import './localRecovery.css'
import './multiProfile.css'
import './bulkLifecycle.css'

createRoot(document.getElementById('root')!).render(<StrictMode><App /><MultiProfileDock /></StrictMode>)
