import { zhCN } from './zh-CN'

type MessageShape<T> = { [K in keyof T]: T[K] extends (...args: infer A) => unknown ? (...args: A) => string : T[K] extends string ? string : MessageShape<T[K]> }

export const en = {
  app: { title: 'Veilium Browser', workspace: 'Veilium workspace', subtitle: 'Multi-profile privacy browser', refresh: 'Refresh data', loading: 'Loading browser environments…', desktopRuntime: 'Desktop runtime', browserPreview: 'Browser preview', desktopEnabled: 'Local process control enabled', previewDisabled: 'Local process execution disabled' },
  nav: { primary: 'Main', advanced: 'Advanced tools', environments: 'Browser environments', network: 'Proxy and network', recovery: 'Data and recovery', batch: 'Batch management', settings: 'Settings', runtime: 'Runtime sessions', kernels: 'Browser kernels', credentials: 'Credentials' },
  common: { create: 'New environment', edit: 'Edit', clone: 'Clone environment', more: 'More', cancel: 'Cancel', save: 'Save', saving: 'Saving…', verify: 'Verify', remove: 'Remove', browse: 'Browse', working: 'Working…', refresh: 'Refresh', details: 'Technical details', defaultGroup: 'Default group', noTags: 'No tags' },
  environments: { eyebrow: 'Browser environment management', title: 'Browser environments', description: 'Create, start and manage isolated browser environments.', searchPlaceholder: 'Search name, group, tag, kernel or proxy…', allGroups: 'All groups', resultCount: (count: number) => `${count} environments`, total: 'All environments', totalDetail: 'Local environment records', ready: 'Ready', readyDetail: 'Checks passed and launch is allowed', running: 'Running', runningDetail: 'Active browser sessions', attention: 'Needs attention', attentionDetail: 'Configuration, dependency or lifecycle limitation', emptyTitle: 'No browser environments yet', emptyDetail: 'Create the first environment, select a browser kernel and network route, then open the browser.', noMatchTitle: 'No matching environments', noMatchDetail: 'Adjust the search or filters.', identity: 'Environment', browser: 'Browser', route: 'Network', identityConfig: 'Identity settings', status: 'Status', actions: 'Actions', openBrowser: 'Open browser', closeBrowser: 'Close browser', startRequiresDesktop: 'Desktop runtime is required to open a browser', startBlocked: 'The current environment state blocks launch', stopBeforeEdit: 'Stop the browser before editing', moveToTrash: 'Move to recoverable trash', moveToTrashConfirm: (name: string) => `Move “${name}” to recoverable trash? Browser data remains recoverable.`, cloneSuffix: 'Copy' },
  network: { eyebrow: 'Network routing', title: 'Proxy and network', description: 'Manage proxy runtimes and verifiable local routes for browser environments.', adapters: 'Proxy adapters', credentials: 'Credential references', sessions: 'Active sessions' },
  recovery: { eyebrow: 'Local data protection', title: 'Data and recovery', description: 'Create same-machine snapshots, archive environments, manage recoverable trash and review operation history.' },
  batch: { eyebrow: 'Bounded multi-environment operations', title: 'Batch management', description: 'Manage multiple environments with fixed selection, preflight, cancellation and per-item results.', operations: 'Operations', lifecycle: 'Lifecycle', profiles: 'Environments', locations: 'Locations', templates: 'Templates', refreshing: 'Refreshing…', refreshData: 'Refresh data' },
  settings: { eyebrow: 'Application settings', title: 'Settings', description: 'Review runtime information, safety boundaries and advanced dependency tools.', runtime: 'Runtime', version: 'Application version', frontendMode: 'Frontend mode', activeSessions: 'Active sessions', dependencies: 'Managed dependencies', kernels: 'Browser kernels', adapters: 'Proxy adapters', automaticDownloads: 'Automatic downloads', disabled: 'Disabled', safety: 'Safety and lifecycle boundary', openRuntime: 'View runtime sessions', openKernels: 'Manage browser kernels', openCredentials: 'Manage credentials' },
  runtime: { eyebrow: 'Local process supervisor', title: 'Runtime sessions', description: 'Inspect browser processes, CDP readiness, logs and exit results.', refresh: 'Refresh sessions', desktopRequired: 'Desktop runtime required', previewNote: 'Browser preview mode cannot start local processes.' },
  kernels: { eyebrow: 'Verified local browsers', title: 'Browser kernels', description: 'Install the reviewed Chromium package or import a custom local Chromium.', customTitle: 'Import custom Chromium', customDescription: 'Custom and legacy files do not inherit reviewed trust.', name: 'Name', provider: 'Provider', version: 'Version', executablePath: 'Executable path', importAndHash: 'Import and hash', emptyTitle: 'No registered browser kernels', emptyDetail: 'Install reviewed Chromium or import a custom executable.', executableSha: 'Executable SHA-256', packageTree: 'Package tree', size: 'Size', managedPath: 'Managed path', removeConfirm: (name: string) => `Remove browser kernel “${name}”?` },
  credentials: { eyebrow: 'Operating-system secure storage', title: 'Credential management', description: 'Passwords stay in the operating-system credential manager and are not written to environment configuration.' },
  editor: { eyebrow: 'Isolated browser environment', createTitle: 'Create browser environment', editTitle: 'Edit browser environment', basic: 'Basic information', basicDetail: 'Set a recognizable name, group, tags and notes.', name: 'Environment name', group: 'Group', tags: 'Tags', tagsHint: 'Separate tags with commas.', notes: 'Notes', browser: 'Browser settings', browserDetail: 'Prefer verified kernels; advanced provider details remain reviewable and do not automatically create trust.', registeredKernel: 'Registered kernel', legacyExecutable: 'Legacy manual executable', kernelHint: 'Integrity verification and provider trust are separate states.', advancedBrowser: 'Advanced browser and provider settings', provider: 'Provider', chromiumVersion: 'Chromium version', executablePath: 'Executable path', providerTrust: 'Provider trust', reviewedTrust: 'Reviewed trust applies only to the exact provider, version, platform and binary identity.', customTrust: 'Custom kernels may use generic launch settings but receive no reviewed fingerprint claims.', legacyTrust: 'Compatibility providers remain readable, but former boolean claims are not treated as verified.', blockedTrust: 'This provider is blocked until its contract is repaired or replaced.', identity: 'Identity settings', identityDetail: 'Keep language, timezone, screen and platform parameters consistent; unsupported controls remain read-only.', platform: 'Operating system', brand: 'Browser brand', language: 'Browser language', timezone: 'Timezone', screenWidth: 'Screen width', screenHeight: 'Screen height', cpuThreads: 'CPU threads', webrtc: 'WebRTC policy', gpuProfile: 'GPU profile', network: 'Network proxy', networkDetail: 'Passwords remain in the operating-system vault; advanced protocols require a verified local adapter.', proxyUrl: 'Proxy URL', credential: 'Credential', noCredential: 'No credential', managedAdapter: 'Managed adapter', selectVerifiedAdapter: 'Select a verified adapter', adapterHint: 'The adapter is verified now and again before each runtime.', adapterRejected: 'The adapter reference will be rejected', adapterRejectedDetail: 'Only VMess, VLESS, Trojan, Shadowsocks, Hysteria2, TUIC and AnyTLS routes use managed adapters.', review: 'Review and save', reviewDetail: 'Saving does not bypass kernel, lifecycle, proxy or capability checks.', reviewReady: 'The backend validates this configuration again. After saving, open the browser from the environment list.', create: 'Create environment', saveChanges: 'Save changes', blockedError: (provider: string, trust: string) => `Provider ${provider} is ${trust} and cannot be saved or launched.` },
} satisfies MessageShape<typeof zhCN>
